---
title : <span style="color:#034A94"> **SEMINARIO**</span>
subtitle: <span style="color:#034A94"> **ANÁLISIS DE TENDENCIAS PARA MÉTODOS CUANTITATIVOS Y CUALITATIVOS**</span>
author: "Pontificia Universidad Javeriana Cali"
css: style.css
---


<br/><br/>

### 
 
<br/>

#### <span style="color:#034A94">**UNIDAD 1 :VALIDA TUS DATOS**</span>

<br/>

* Introducción a la calidad de la información
* Fuentes de información.
* Variables cualitativas y cuantitativas
* Identificación de errores y sesgos en la información

<br/><br/>

#### <span style="color:#034A94">**UNIDAD 2: CONTROL INTERNO**</span>

<br/>

* Conceptos básicos: indicadores de posición, centro, dispersión y forma
* La media muestral, la proporción muestral y la varianza muestral.
* modelos binomiales, poisson y normal.  
* Introducción al control de calidad
* Gráficos e indicadores de control de calidad. 
* Control interno.  Cartas de control, Reglas de control 
* Análisis de Ensayos de Aptitud y Z-Score
* Control interno y Seguimiento de Tendencias
* Análisis de control binario y T2 de Hotelling

<br/><br/>

#### <span style="color:#034A94">**UNIDAD 3: GENERALIZA LOS RESULTADOS**</span>

<br/>

* Estimación puntual y por intervalos de confianza
* Pruebas de hipótesis: 
  * Conceptos, 
  * Error tipo I, 
  * Error tipo II 
  * Potencia de las pruebas de hipótesis. 
* Pruebas paramétricas 
* Pruebas de hipótesis no paramétricas
* Evaluación de la significancia estadística
* Modelo de regresión y curvas de calibración

<br/><br/>

#### <span style="color:#034A94">**UNIDAD 4: INTERPRETA Y PRESENTA TUS RESULTADOS**</span>

<br/>

* Análisis y discusión de resultados científicos
* Aplicación de los Conceptos a Casos prácticos


<br/><br/>

 